From roelofs@sonic.net  Sun Apr  9 15:11:45 2000
Return-Path: roelofs@sonic.net
Received: from wormwood.pobox.com (wormwood.pobox.com [208.210.124.20])
	by prop.sonic.net (8.8.8/8.8.5) with ESMTP id PAA24215
	for <roelofs@sonic.net>; Sun, 9 Apr 2000 15:11:44 -0700
Received: by wormwood.pobox.com (Postfix, from userid 1001)
	id E7F7C64DA5; Sun,  9 Apr 2000 18:12:37 -0400 (EDT)
Received: from marine.sonic.net (marine.sonic.net [208.201.224.37])
	by wormwood.pobox.com (Postfix) with SMTP id D11F764DAD
	for <newt@pobox.com>; Sun,  9 Apr 2000 18:12:36 -0400 (EDT)
Received: (qmail 8875 invoked from network); 9 Apr 2000 22:11:40 -0000
Received: from prop.sonic.net (208.201.224.193)
  by marine.sonic.net with SMTP; 9 Apr 2000 22:11:40 -0000
Received: from sonic.net (bolt [208.201.224.36])
	by prop.sonic.net (8.8.8/8.8.5) with ESMTP id PAA24184;
	Sun, 9 Apr 2000 15:11:36 -0700
X-envelope-info: <roelofs@sonic.net>
Received: (from roelofs@localhost) by sonic.net (8.8.8/8.7.3) id PAA20023; Sun, 9 Apr 2000 15:11:27 -0700
Date: Sun, 9 Apr 2000 15:11:27 -0700
Message-Id: <200004092211.PAA20023@sonic.net>
From: Greg Roelofs <newt@pobox.com>
To: crypt@bxa.doc.gov
Subject: notice of export of unrestricted encryption source code
Cc: newt@pobox.com, zip-bugs@lists.wku.edu
Sender: roelofs@sonic.net
Status: R

The Info-ZIP group, an informal, Internet-based collection of software
developers with contact address Zip-Bugs@lists.wku.edu, hereby notifies
the US Bureau of Export Administration (BXA) of the posting of freely
available encryption source code on the Internet under License Exception
TSU, to commence later today at this location:

	ftp://ftp.info-zip.org/pub/infozip/src/zcrypt.zip

This notification is in accordance with section 740.13(e) of the amended
Export Administration Regulations, as published in the 14 January 2000
issue of the Federal Register.

-- 
Greg Roelofs            newt@pobox.com            http://pobox.com/~newt/
Newtware, PNG Group, Info-ZIP, Philips Research, ...

